import type { DashboardData, NewsItem, StarshipFlight } from '../types';

/** Curated Starship integrated-flight-test history (fallback when API unavailable). */
export const FALLBACK_FLIGHTS: StarshipFlight[] = [
  {
    id: 'ift-1',
    flightNumber: 1,
    name: 'IFT-1',
    dateUtc: '2023-04-20T13:33:00Z',
    site: 'Starbase, TX',
    outcome: 'failure',
    summary: 'First integrated flight. Stage separation failed; vehicle lost at ~39 km.',
    milestones: ['First full-stack launch', 'Reached supersonic flight'],
    reachedSpace: false,
  },
  {
    id: 'ift-2',
    flightNumber: 2,
    name: 'IFT-2',
    dateUtc: '2023-11-18T13:02:00Z',
    site: 'Starbase, TX',
    outcome: 'failure',
    summary: 'Hot-staging demonstrated. Ship lost after reaching space.',
    milestones: ['Hot-staging', 'Reached space (~150 km)'],
    reachedSpace: true,
  },
  {
    id: 'ift-3',
    flightNumber: 3,
    name: 'IFT-3',
    dateUtc: '2024-03-14T13:25:00Z',
    site: 'Starbase, TX',
    outcome: 'failure',
    summary: 'Reached planned suborbital trajectory. Ship lost during reentry.',
    milestones: ['Payload door demo', 'On-orbit propellant transfer demo'],
    reachedSpace: true,
  },
  {
    id: 'ift-4',
    flightNumber: 4,
    name: 'IFT-4',
    dateUtc: '2024-06-06T12:50:00Z',
    site: 'Starbase, TX',
    outcome: 'partial',
    summary: 'Soft splashdown in Gulf of Mexico. Booster soft-landed in Gulf.',
    milestones: ['Controlled reentry', 'Booster soft splashdown'],
    reachedSpace: true,
  },
  {
    id: 'flight-5',
    flightNumber: 5,
    name: 'Flight 5',
    dateUtc: '2024-10-13T12:25:00Z',
    site: 'Starbase, TX',
    outcome: 'success',
    summary: 'First booster catch at Mechazilla. Ship soft-landed in Indian Ocean.',
    milestones: ['Tower catch (chopsticks)', 'Ship soft splashdown'],
    reachedSpace: true,
  },
  {
    id: 'flight-6',
    flightNumber: 6,
    name: 'Flight 6',
    dateUtc: '2024-11-19T22:00:00Z',
    site: 'Starbase, TX',
    outcome: 'success',
    summary: 'Repeat booster catch. Ship completed controlled reentry and splashdown.',
    milestones: ['Second booster catch', 'Raptor relight in space'],
    reachedSpace: true,
  },
  {
    id: 'flight-7',
    flightNumber: 7,
    name: 'Flight 7',
    dateUtc: '2025-01-16T22:37:00Z',
    site: 'Starbase, TX',
    outcome: 'partial',
    summary: 'Upgraded ship (Block 2). Booster catch missed; ship splashdown achieved.',
    milestones: ['Block 2 ship debut', 'New forward flaps'],
    reachedSpace: true,
  },
  {
    id: 'flight-8',
    flightNumber: 8,
    name: 'Flight 8',
    dateUtc: '2025-03-06T23:30:00Z',
    site: 'Starbase, TX',
    outcome: 'failure',
    summary: 'Multiple Raptor failures on ascent. Ship and booster lost.',
    milestones: ['V3 booster pathfinder'],
    reachedSpace: false,
  },
  {
    id: 'flight-9',
    flightNumber: 9,
    name: 'Flight 9',
    dateUtc: '2025-05-27T23:36:00Z',
    site: 'Starbase, TX',
    outcome: 'partial',
    summary: 'Booster returned to pad; ship lost during aggressive reentry test.',
    milestones: ['Booster catch', 'High-angle reentry test'],
    reachedSpace: true,
  },
  {
    id: 'flight-10',
    flightNumber: 10,
    name: 'Flight 10',
    dateUtc: '2025-08-26T23:30:00Z',
    site: 'Starbase, TX',
    outcome: 'success',
    summary: 'Successful booster catch and ship splashdown in target zone.',
    milestones: ['Block 2 ship refinement', 'Night launch'],
    reachedSpace: true,
  },
  {
    id: 'flight-11',
    flightNumber: 11,
    name: 'Flight 11',
    dateUtc: '2025-10-13T23:10:00Z',
    site: 'Starbase, TX',
    outcome: 'success',
    summary: 'Demonstrated rapid turnaround cadence. Full mission profile success.',
    milestones: ['Payload deployment demo', 'Booster catch'],
    reachedSpace: true,
  },
  {
    id: 'flight-12',
    flightNumber: 12,
    name: 'Flight 12',
    dateUtc: '2026-05-22T23:15:00Z',
    site: 'Starbase, TX',
    outcome: 'success',
    summary: 'Latest flight as of June 2026. Booster catch and ship splashdown.',
    milestones: ['V3 ship hardware', 'Increased propellant load'],
    reachedSpace: true,
  },
  {
    id: 'flight-13',
    flightNumber: 13,
    name: 'Flight 13',
    dateUtc: '2026-08-15T00:00:00Z',
    site: 'Starbase, TX',
    outcome: 'upcoming',
    summary: 'Next integrated flight test — targeting ship recovery improvements and higher cadence.',
    milestones: ['Ship landing zone test', 'Booster catch repeat'],
    reachedSpace: false,
  },
];

export const FALLBACK_NEWS: NewsItem[] = [
  {
    id: 'n1',
    title: 'Flight 12 completes with booster catch and ship splashdown',
    date: '2026-05-23',
    source: 'SpaceX',
    url: 'https://www.spacex.com/launches',
    tag: 'flight',
  },
  {
    id: 'n2',
    title: 'Starbase pad upgrades continue ahead of Flight 13',
    date: '2026-06-15',
    source: 'NASASpaceflight',
    url: 'https://www.youtube.com/@NASASpaceflight',
    tag: 'infrastructure',
  },
  {
    id: 'n3',
    title: 'Starship HLS variant progressing toward lunar demo milestones',
    date: '2026-06-01',
    source: 'SpaceX Updates',
    url: 'https://www.spacex.com/updates',
    tag: 'milestone',
  },
  {
    id: 'n4',
    title: 'FAA license window opens for next Starship flight test campaign',
    date: '2026-06-20',
    source: 'SpaceX',
    url: 'https://www.spacex.com/vehicles/starship',
    tag: 'update',
  },
];

export function buildFallbackDashboard(): DashboardData {
  const completed = FALLBACK_FLIGHTS.filter((f) => f.outcome !== 'upcoming');
  const successes = completed.filter((f) => f.outcome === 'success').length;
  const partials = completed.filter((f) => f.outcome === 'partial').length;
  const reachedSpace = completed.filter((f) => f.reachedSpace).length;
  const year = new Date().getFullYear();

  return {
    flights: FALLBACK_FLIGHTS,
    metrics: {
      totalFlights: FALLBACK_FLIGHTS.length,
      completedFlights: completed.length,
      reachedSpace,
      successRate: completed.length
        ? Math.round(((successes + partials * 0.5) / completed.length) * 100)
        : 0,
      flights2026: FALLBACK_FLIGHTS.filter(
        (f) => new Date(f.dateUtc).getFullYear() === year && f.outcome !== 'upcoming',
      ).length,
      nextFlightNumber: 13,
    },
    news: FALLBACK_NEWS,
    nextLaunchDate: '2026-08-15T00:00:00Z',
    rocketName: 'Starship',
    dataSource: 'fallback',
    lastUpdated: new Date().toISOString(),
  };
}